### PR TITLE
Update Master

### PR DESCRIPTION
**Pull request by bobheadxi**
Waiting for build pass
https://github.com/d4rken/reddit-android-appstore/releases/tag/v0.7.1
https://github.com/d4rken/reddit-android-appstore/releases/tag/untagged-a382da6d63b6a57edf44

### CODE REVIEW

**Comment by bobheadxi** [comment]
Just updated coveralls setting on the site, it should no longer fail builds for decreased coverage, not sure why it decreased in the first place though

**Comment by d4rken** [comment]
More lines of code, same tests, so decreased overall coverage?

**Comment by bobheadxi** [comment]
Going from the [last build](https://coveralls.io/builds/12516998) to the [subsequent build](https://coveralls.io/builds/12523393) saw a 0.2% decrease despite only being a version number update

Newly missed lines [here](https://coveralls.io/builds/12523393/source?filename=app%2Fsrc%2Fmain%2Fjava%2Fsubreddit%2Fandroid%2Fappstore%2FAppStoreApp.java#L33), looks like some version number related things

**Comment by d4rken** [comment]
@bobheadxi Btw is was mistaken, only owner/collaborators can see the draft.

**Pull request merged**
