### PR TITLE
Issue #44: Show changelog of latest release

### PR DESCRIPTION
**Pull request by bobheadxi**
- Tapping the snackbar link or sidebar "Update Available" link will now open a changelog dialog
- Dialog displays release tag, release name, date of release and the release description:
screenshot_20170622-221353
- Updated FakeSelfUpdater

### CODE REVIEW

**Comment by d4rken** [comment]
Nice, thanks for all the contributions.

**Comment by d4rken** [comment]
Now we need to test the dev branch to make sure it all works as expected, and then we can release an update.

**Comment by bobheadxi** [comment]
Nice! Is there any particular procedure for that?

**Comment by d4rken** [comment]
In a perfect world we would have lots of unit tests and instrumentation tests 😁, but I think we'll just have to play around with the app 😉 .

Timewise I'm limited atm, if you say it works and is good for a release, we'll make a release build.

Made #96 for this, if you say it's good I'll post the release apk there so that can be tested too (this is usually only an issue though [if proguard is enabled](https://github.com/d4rken/reddit-android-appstore/blob/dev/app/build.gradle#L44)).

**Comment by bobheadxi** [comment]
Thanks for the collaboration invite! 💯 
I am not going to have as much time in the coming month but I'm actually hoping to start putting together the unit and instrumentation tests before working on more features for 0.8.0 - I understand that you're pretty limited on time but if you could point me to any good resources that I might not know of in regards to unit testing on Android that would great :) Thank you for all the feedback!

**Comment by d4rken** [comment]
Look into Mockito for unit and instrumentation testing, and into Espresso for instrumentation testing.

Instrumentation testing is usually the more difficult part as the architecture needs to support it from the ground up to be really useful. For unit testing you just need the classes to be modular, which usually ends up with quite a lot of things being passed via constructor.

My current choice for instrumentation testing is leveraging daggers new android injectors such that you can instance an activity/fragment an pass in a mock component that supplies it's dependencies, mainly the presenter.

Started on an [little library](https://github.com/d4rken/ommvplib) to help with such an mvp/dagger architecture, but it's very "alpha" still and doesn't have a good example for instrumentation testing yet...

I'd probably just start with unit tests, possibly refactor to have nice small testable modules 😄 .

**Comment by bobheadxi** [comment]
@d4rken 
> I'd probably just start with unit tests, possibly refactor to have nice small testable modules

Sorry, but I'm struggling to understand what you mean here: do you mean separate stuff out from the `:app` module into separate modules, ie `:backend`? Wouldn't that cause a lot of problems with circular dependencies? How would I go about doing this?

**Comment by d4rken** [comment]
I just meant to do refactoring such that individual functions can be testet well because their dependency can be easily injected.

**Pull request merged**
