### PR TITLE
Specify Javapoet version

### PR DESCRIPTION
**Pull request by bobheadxi**
^

### CODE REVIEW

**Comment by d4rken** [comment]
What does this do?

**Comment by bobheadxi** [comment]
@d4rken It doesn't seem to be an issue with anyone else or Travis, but `GlideApp` was not generating for me despite rebuilds, etc. I looked around and a post somewhere mentioned that Dagger comes bundled with its own version of Javapoet and that it caused issues with Glide's annotationProcessor. So I added the `compile` and the GlideApp was generated. A bit odd.

Sorry about that, forgot to link it, the comment I made is [here](https://github.com/d4rken/reddit-android-appstore/pull/115#issuecomment-320692924) and the post about Javapoet is [here](https://github.com/rharter/auto-value-gson/issues/43)

Now that I think about it `@AnnotationProcessor` might have been more suitable than `@Compile` hm

**Comment by d4rken** [comment]
Weird that this only affects you. Have you tried clearing your build cache and seeing if this persists?

When adding "workaround-code" I think it's good to also add a comment in code linking to an issue ticket with more details.

**Comment by bobheadxi** [comment]
I tried invalidating cache, removing the project entirely, clean/rebuild/make etc.

That is a good point, I will keep that in mind, definitely need to work on commenting. thank you

**Pull request merged**
