### PR TITLE
Prepend global tag to Timber debug tree

### PR DESCRIPTION
**Pull request by veyndan**
This saves having to manually set the tag for each Timber log call. [Here's a link](https://www.reddit.com/r/androiddev/comments/4zfkup/an_easy_way_to_add_a_universal_tag_to_all_timber/) to a Reddit post I made a few weeks ago about how I solved this exact same problem before.

### CODE REVIEW

**Comment by d4rken** [comment]
Now all items have only the global tag though, because you removed the `tag(...)` from all calls. Every logoutput is now just tagged with `RAS:`.

**Comment by veyndan** [comment]
Use of `tag(…)` should be the exception not the rule. The debug tree by default tags each log with the class name. By prepending the`RAS:` to the default debug logs (which I have done), each output is now in the for `RAS:<class-name>`.

**Comment by d4rken** [comment]
Good point, forgot about the classnames being taken by default.
Thanks!

Note that this can become tricky, if an app uses proguard to obfuscates classnames.

**Comment by veyndan** [comment]
Interesting, hadn't thought about the potential problems with proguard. Though as it's open source, it doesn't matter anyway.

**Pull request merged**
